# Generated by Django 5.0.3 on 2024-03-24 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_management.employee'),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_management.employee'),
        ),
        migrations.AddField(
            model_name='workedhours',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_management.employee'),
        ),
        migrations.AddField(
            model_name='workedhours',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_management.shift'),
        ),
    ]
